ktor:
  application:
    modules:
      - tech.nimbus.ApplicationKt.module
  development: false

jwt:
  secret: ${?JWT_SECRET}
  issuer: ${?JWT_ISSUER}
  audience: ${?JWT_AUDIENCE}
  realm: ${?JWT_REALM}

database:
  url: ${?DATABASE_URL}
  driver: "org.postgresql.Driver"
  user: ${?DB_USER}
  password: ${?DB_PASSWORD}
